[workspace]
members = ["00_time", "01_space", "02_instances", "03_grid", "04_sprites", "05_animation", "06_death", "07_sound", "08_blend"]

resolver = "3"

# [profile.release]
# opt-level="s"
# debug=false
# lto="thin"
# panic="abort"
# codegen-units=1
# strip="symbols"


[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
# arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"

missing_const_for_fn ="allow"
future_not_send = "allow"

