[workspace]
members = ["00_time", "01_space", "02_instances", "03_grid", "04_sprites", "05_animation"]

resolver = "3"

# [profile.release]
# opt-level="s"
# debug=false
# lto="thin"
# panic="abort"
# codegen-units=1
# strip="symbols"


[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"

missing_const_for_fn ="allow"
cast_possible_truncation = "allow"
cast_precision_loss= "allow"
cast_sign_loss = "allow"
future_not_send = "allow"
# expect_used = "deny"
# as_conversions = "deny"
# indexing_slicing = "deny"
# arithmetic_side_effects = "deny"
# todo = "deny"
